---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 17:40
---
return {
    codes = require('enums.http.codes'),
    methods = require('enums.http.methods')
}
