---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 18/02/2024 01:26
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local mapper = require('utils.mapper')

local get_calendars = {
    query = [[
        SELECT
            ID AS id,
            Name AS name,
            ReferenceDate AS reference_date,
            NegativeYears AS negative_years
        FROM Calendars
    ]]
}

function get_calendars.execute(_, response)
    local calendars = {}
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_calendars.query)
    calendars = mapper.fetch_results.as_table(result, {
        id = tonumber,
        negative_years = tonumber
    })

    response:write(json.encode(calendars))
    result:close()
    connection:close()
    env:close()
end

return get_calendars
