---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 18/02/2024 01:26
---
local json = require('lunajson')
local connector = require('utils.database_connection')

local get_calendars = {
    query = [[
        SELECT
            ID AS id,
            Name AS name,
            ReferenceDate AS reference_date,
            NegativeYears AS negative_years
        FROM Calendars
    ]]
}

function get_calendars.execute(_, response)
    local calendars = {}
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_calendars.query)
    calendars = get_calendars.fetch_results(result)

    response:write(json.encode(calendars))
    result:close()
    connection:close()
    env:close()
end

function get_calendars.fetch_results(result)
    local calendars = {}
    local row = result:fetch({}, "a")

    local i = 1
    while row do
        calendars[i] = row

        row = result:fetch({}, "a")
        i = i + 1
    end

    return calendars
end

return get_calendars
