---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 10:46
---
local pegasus = require('pegasus')
local routing = require('routing')

local server = pegasus:new({}) -- creating a server with the default configuration
server:start(routing.dispatch)
