---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 24/02/2024 11:59
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local mapper = require('utils.mapper')
local prototype = require('entities.map')

local get_maps = {
    query = [[
        SELECT
            ID AS id,
            Name AS name,
            EstablishmentDate AS establishment_date,
            ExpiryDate AS expiry_date,
            Nation AS nation
        FROM Maps
    ]]
}

function get_maps.execute(_, response)
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_maps.query)
    local maps = mapper.fetch_results.as_object(result, prototype)

    response:write(json.encode(maps))
    result:close()
    connection:close()
    env:close()
end

return get_maps
