---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 07/03/2024 21:21
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local http = require('enums.http_facade')
local prototype = require('entities.map')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')

local post_maps = {
    query = [[
        INSERT INTO Maps
        (
            Name,
            EstablishmentDate,
            ExpiryDate,
            Nation,
            Content
        )
        VALUES

    ]],

    value = "(%s, %s, %s, %s, '')"
}

function post_maps.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local new_maps = json.decode(request:receiveBody())
    local query = query_builder.create_insert_query(
            post_maps.query,
            post_maps.value,
            prototype,
            new_maps,
            escaper
    )


    if type(query) ~= "string" then
        post_maps.lacking_data(response, query, connection, env)
        return
    end
    if not connection:execute(query) then
        post_maps.foreign_value_not_found(response, connection, env)
        return
    end

    response
            :statusCode(http.codes.CREATED)
            :sendOnlyHeaders()
    post_maps.close(connection, env)
end

function post_maps.lacking_data(response, entity, connection, env)
    response
            :statusCode(http.codes.BAD_REQUEST)
            :write(json.encode({ message = "Detected missing values in this entity", map = entity }))
    post_maps.close(connection, env)
end

function post_maps.foreign_value_not_found(response, connection, env)
    response
            :statusCode(http.codes.NOT_FOUND)
            :write(json.encode({ message = "Nation not found!" }))
    post_maps.close(connection, env)
end

function post_maps.close(connection, env)
    connection:close()
    env:close()
end

return post_maps
