---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 11/03/2024 20:06
---
local connector = require('utils.database_connection')
local escaper = require('utils.extra_function_escape')
local errors = require('utils.errors')
local http = require('enums.http_facade')

local post_map_content = {
    query = [[
        UPDATE Maps
        SET Content = '%s'
        WHERE ID = %s
    ]]
}

function post_map_content.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local content = request:receiveBody() -- content bytes
    local id = string.sub(string.match(request:path(), "/%d+/"), 2, -2)
    local query = string.format(post_map_content.query, escaper.apply(content), id)

    if not connection:execute(query) then
        errors.foreign_value_not_found(response, { "map" }, connection, env)
        return
    end

    response
            :statusCode(http.codes.CREATED)
            :sendOnlyHeaders()
    post_map_content.close(connection, env)
end

function post_map_content.close(connection, env)
    connection:close()
    env:close()
end

return post_map_content
