---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 24/02/2024 12:35
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local mapper = require('utils.mapper')
local prototype = require('entities.nation')

local get_nations = {
    query = [[
        SELECT
            ID AS id,
            Name AS name,
            Calendar AS calendar,
            FoundationDate AS foundation_date,
            DestructionDate AS destruction_date,
            Description AS description
        FROM Nations
    ]]
}

function get_nations.execute(_, response)
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_nations.query)
    local nations = mapper.fetch_results.as_object(result, prototype)

    response:write(json.encode(nations))
    result:close()
    connection:close()
    env:close()
end

return get_nations
