---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 07/03/2024 21:31
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local http = require('enums.http_facade')
local prototype = require('entities.nation')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')

local post_nations = {
    query = [[
        INSERT INTO Nations
        (
            Name,
            Calendar,
            FoundationDate,
            DestructionDate,
            Description
        )
        VALUES

    ]],

    value = "(%s, %s, %s, %s, %s)"
}

function post_nations.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local new_nations = json.decode(request:receiveBody())
    local query = query_builder.create_insert_query(
            post_nations.query,
            post_nations.value,
            prototype,
            new_nations,
            escaper
    )


    if type(query) ~= "string" then
        post_nations.lacking_data(response, query, connection, env)
        return
    end
    if not connection:execute(query) then
        post_nations.foreign_value_not_found(response, connection, env)
        return
    end

    response
            :statusCode(http.codes.CREATED)
            :sendOnlyHeaders()
    post_nations.close(connection, env)
end

function post_nations.lacking_data(response, entity, connection, env)
    response
            :statusCode(http.codes.BAD_REQUEST)
            :write(json.encode({ message = "Detected missing values in this entity", nation = entity }))
    post_nations.close(connection, env)
end

function post_nations.foreign_value_not_found(response, connection, env)
    response
            :statusCode(http.codes.NOT_FOUND)
            :write(json.encode({ message = "Calendar not found!" }))
    post_nations.close(connection, env)
end

function post_nations.close(connection, env)
    connection:close()
    env:close()
end

return post_nations
