---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 11/03/2024 10:15
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local prototype = require('entities.link_charac_magic')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')
local errors = require('utils.errors')

local put_characs_magics = {
    vocab = {
        table_name = "LINK_CharacsMagics",
        primary_key = { db = "ID", prop = "id" },
        editable_columns = {
            charac = "Charac",
            magic = "Magic",
            rank = "`Rank`"
        }
    }
}

function put_characs_magics.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local edited_characs_magics = json.decode(request:receiveBody())
    local queries = query_builder.create_update_queries(
            put_characs_magics.vocab,
            prototype,
            edited_characs_magics,
            escaper
    )

    if type(queries) ~= "string" then
        errors.incorrect_data(response, { charac = queries }, connection, env)
        return
    end
    if not connection:execute(queries) then
        errors.foreign_value_not_found(
                response,
                { "character", "calendar", "class", "sex", "gender", "origin" },
                connection,
                env
        )
        return
    end

    response:sendOnlyHeaders()
    put_characs_magics.close(connection, env)
end

function put_characs_magics.close(connection, env)
    connection:close()
    env:close()
end

return put_characs_magics
