---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 22/02/2024 11:53
---
local http = require('enums.http_facade')
local delete = require('use_cases.generic.delete')

local delete_charac_events = {
    vocabulary = {
        table = "CharacEvents",
        id_column = "ID",
        querystring_property_name = "ids"
    }
}

function delete_charac_events.execute(request, response)
    delete
        .set_id_column(delete_charac_events.vocabulary.id_column)
        .set_queried_table(delete_charac_events.vocabulary.table)
        .set_querystring_property_name(delete_charac_events.vocabulary.querystring_property_name)

    if not delete.execute(request, response) then
        response
            :statusCode(http.codes.NOT_FOUND)
            :sendOnlyHeaders()
    end

    response:sendOnlyHeaders()
end

return delete_charac_events
