---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 19/02/2024 10:50
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local prototype = require('entities.charac_event')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')
local errors = require('utils.errors')

local put_charac_events = {
    vocab = {
        table_name = "CharacEvents",
        primary_key = { db = "ID", prop = "id" },
        editable_columns = {
            starting_date = "StartingDate",
            ending_date = "EndingDate",
            charac = "Charac",
            description = "Description"
        }
    }
}

function put_charac_events.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local edited_events = json.decode(request:receiveBody())
    local queries = query_builder.create_update_queries(
            put_charac_events.vocab,
            prototype,
            edited_events,
            escaper
    )

    if type(queries) ~= "string" then
        errors.incorrect_data(response, { event = queries }, connection, env)
        return
    end
    if not connection:execute(queries) then
        errors.foreign_value_not_found(
                response,
                { "character", "character event" },
                connection,
                env
        )
        return
    end

    response:sendOnlyHeaders()
    put_charac_events.close(connection, env)
end

function put_charac_events.close(connection, env)
    connection:close()
    env:close()
end

return put_charac_events
