---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 22:58
---
local types_default = require('utils.types_default')

charac_relationship = {}

function charac_relationship:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_default.number
    instance.from_charac = mapped_fields.from_charac or mapped_fields[2] or types_default.number
    instance.towards_charac = mapped_fields.towards_charac or mapped_fields[3] or types_default.number
    instance.family_status = mapped_fields.family_status or mapped_fields[4] or nil
    instance.appreciation = mapped_fields.appreciation or mapped_fields[5] or types_default.number
    instance.history = mapped_fields.history or mapped_fields[6] or nil

    return setmetatable(instance, self)
end

return charac_relationship
