---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 22:36
---
local types_default = require('utils.types_default')

charac = {}

function charac:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_default.number
    instance.last_names = mapped_fields.last_names or mapped_fields[2] or types_default.string
    instance.first_names = mapped_fields.first_names or mapped_fields[3] or types_default.string
    instance.portrait = mapped_fields.portrait or mapped_fields[4] or nil
    instance.description = mapped_fields.description or mapped_fields[5] or nil
    instance.calendar = mapped_fields.calendar or mapped_fields[6] or types_default.number
    instance.birthdate = mapped_fields.birthdate or mapped_fields[7] or types_default.string
    instance.deathdate = mapped_fields.deathdate or mapped_fields[8] or nil
    instance.magical_potential = mapped_fields.magical_potential or mapped_fields[9] or nil
    instance.class = mapped_fields.class or mapped_fields[10] or nil
    instance.sex = mapped_fields.sex or mapped_fields[11] or types_default.number
    instance.gender = mapped_fields.gender or mapped_fields[12] or nil
    instance.sexual_orientation = mapped_fields.sexual_orientation or mapped_fields[13] or nil
    instance.origin = mapped_fields.origin or mapped_fields[14] or nil
    instance.height = mapped_fields.height or mapped_fields[15] or nil
    instance.hair_colour = mapped_fields.hair_colour or mapped_fields[16] or nil
    instance.eye_colour = mapped_fields.eye_colour or mapped_fields[17] or nil
    instance.appearance = mapped_fields.appearance or mapped_fields[18] or nil
    instance.favourite_colour = mapped_fields.favourite_colour or mapped_fields[19] or nil
    instance.things_loved = mapped_fields.things_loved or mapped_fields[20] or types_default.table
    instance.things_hated = mapped_fields.things_hated or mapped_fields[21] or types_default.table

    return setmetatable(instance, self)
end

return charac
