---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 22:09
---
local types_defaults = require('utils.types_default')

charac_event = {
    properties = {
        id              = { format = tonumber },
        starting_date   = { format = tostring },
        ending_date     = { format = tostring },
        charac          = { format = tonumber },
        description     = { format = tostring }
    },

    insert_property_order = {
        "starting_date", "ending_date", "charac", "description"
    },

    update_property_order = {
        "id", "starting_date", "ending_date", "charac", "description"
    }
}

function charac_event:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_defaults.number
    instance.starting_date = mapped_fields.starting_date or mapped_fields[2] or types_defaults.string
    instance.ending_date = mapped_fields.ending_date or mapped_fields[3] or types_defaults.string
    instance.charac = mapped_fields.charac or mapped_fields[4] or types_defaults.number
    instance.description = mapped_fields.description or mapped_fields[5] or types_defaults.string

    return setmetatable(instance, self)
end

return charac_event
