---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 23:07
---
local types_default = require('utils.types_default')

link_charac_magic = {}

function link_charac_magic:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_default.number
    instance.charac = mapped_fields.charac or mapped_fields[2] or types_default.number
    instance.magic = mapped_fields.magic or mapped_fields[3] or types_default.number
    instance.rank = mapped_fields.rank or mapped_fields[4] or types_default.number

    return setmetatable(instance, self)
end

return link_charac_magic
