---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 23:13
---
local types_default = require('utils.types_default')

magic = {
    properties = {
        id = { format = tonumber },
        name = { format = tostring },
        description = { format = tostring, nullable = true }
    },

    insert_property_order = { "name", "description" },

    update_property_order = { "id", "name", "description" }
}

function magic:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_default.number
    instance.name = mapped_fields.name or mapped_fields[2] or types_default.string
    instance.description = mapped_fields.description or mapped_fields[3] or nil

    return setmetatable(instance, self)
end

return magic
