---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 23:15
---
local types_default = require('utils.types_default')

map = {
    properties = {
        id = { format = tonumber },
        name = { format = tostring },
        establishment_date = { format = tostring },
        expiry_date = { format = tostring },
        nation = { format = tonumber },
        content = { format = tostring }
    }
}

function map:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_default.number
    instance.name = mapped_fields.name or mapped_fields[2] or types_default.string
    instance.establishment_date = mapped_fields.establishment_date or mapped_fields[3] or nil
    instance.expiry_date = mapped_fields.expiry_date or mapped_fields[4] or nil
    instance.nation = mapped_fields.nation or mapped_fields[5] or nil
    instance.content = mapped_fields.content or mapped_fields[6] or types_default.string

    return setmetatable(instance, self)
end

return map