---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 23:23
---
local types_default = require('utils.types_default')

nation_leader = {
    properties = {
        id = { format = tonumber },
        leader = { format = tonumber },
        nation = { format = tonumber },
        lead_start_date = { format = tostring },
        lead_end_date = { format = tostring, nullable = true }
    },

    insert_property_order = { "leader", "nation", "lead_start_date", "lead_end_date" },

    udpate_property_order = { "id", "leader", "nation", "lead_start_date", "lead_end_date" }
}

function nation_leader:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_default.number
    instance.leader = mapped_fields.leader or mapped_fields[2] or types_default.number
    instance.nation = mapped_fields.nation or mapped_fields[3] or types_default.number
    instance.lead_start_date = mapped_fields.lead_start_date or mapped_fields[4] or types_default.string
    instance.lead_end_date = mapped_fields.lead_end_date or mapped_fields[4] or nil

    return setmetatable(instance, self)
end

return nation_leader
