---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/02/2024 23:26
---
local types_default = require('utils.types_default')

sex = {
    properties = {
        id = { format = tonumber },
        name = { format = tostring }
    }
}

function sex:new(mapped_fields)
    mapped_fields = mapped_fields or {}
    local instance = {}

    instance.id = mapped_fields.id or mapped_fields[1] or types_default.number
    instance.name = mapped_fields.name or mapped_fields[2] or types_default.string

    return setmetatable(instance, self)
end

return sex