---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 23/02/2024 23:37
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local mapper = require('utils.mapper')

local get_family_statuses = {
    query = [[
        SELECT
            ID AS id,
            Name AS name
        FROM FamilyStatuses
    ]]
}

function get_family_statuses.execute(_, response)
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_family_statuses.query)
    local family_statuses = mapper.fetch_results.as_table(result, {
        id = tonumber
    })

    response:write(json.encode(family_statuses))
    result:close()
    connection:close()
    env:close()
end

return get_family_statuses
