---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 11/03/2024 19:51
---
local connector = require('utils.database_connection')
local errors = require('utils.errors')

local delete_charac_portrait = {
    query = [[
        UPDATE Characs
        SET Portrait = NULL
        WHERE ID = %s
    ]]
}

function delete_charac_portrait.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end

    local id = string.sub(string.match(request:path(), "/%d+/"), 2, -2)
    local query = string.format(delete_charac_portrait.query, id)

    if not connection:execute(query) then
        errors.foreign_value_not_found(response, { "character" }, connection, env)
        return
    end

    response:sendOnlyHeaders()
    delete_charac_portrait.close(connection, env)
end

function delete_charac_portrait.close(connection, env)
    connection:close()
    env:close()
end

return delete_charac_portrait
