---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 22/02/2024 13:34
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local mapper = require('utils.mapper')
local prototype = require('entities.charac')

local get_characs = {
    query = [[
        SELECT
            ID AS id,
            LastNames AS last_names,
            FirstNames AS first_names,
            Description AS description,
            Calendar AS calendar,
            Birthdate AS birthdate,
            Deathdate AS deathdate,
            MagicalPotential AS magical_potential,
            Class AS class,
            Sex AS sex,
            Gender AS gender,
            SexualOrientation AS sexual_orientation,
            Origin AS origin,
            Height AS height,
            HairColour AS hair_colour,
            EyeColour AS eye_colour,
            Appearance AS appearance,
            FavoriteColour AS favourite_colour,
            ThingsLoved AS things_loved,
            ThingsHated AS things_hated
        FROM Characs
    ]]
}

function get_characs.execute(_, response)
    local characs = {}
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_characs.query)
    characs = mapper.fetch_results.as_object(result, prototype)

    response:write(json.encode(characs))
    result:close()
    connection:close()
    env:close()
end

return get_characs