---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 11/03/2024 14:45
---
local connector = require('utils.database_connection')
local escaper = require('utils.extra_function_escape')
local errors = require('utils.errors')
local http = require('enums.http_facade')

local post_charac_portrait = {
    query = [[
        UPDATE Characs
        SET Portrait = '%s'
        WHERE ID = %s
    ]]
}

function post_charac_portrait.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local portrait = request:receiveBody() -- portrait bytes
    local id = string.sub(string.match(request:path(), "/%d+/"), 2, -2)
    local query = string.format(post_charac_portrait.query, escaper.apply(portrait), id)

    if not connection:execute(query) then
        errors.foreign_value_not_found(response, { "character" }, connection, env)
        return
    end

    response
            :statusCode(http.codes.CREATED)
            :sendOnlyHeaders()
    post_charac_portrait.close(connection, env)
end

function post_charac_portrait.close(connection, env)
    connection:close()
    env:close()
end

return post_charac_portrait
