---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 24/02/2024 11:46
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local mapper = require('utils.mapper')
local prototype = require('entities.link_elems_magics')

local get_link_elems_magics = {
    query = [[
        SELECT
            ID AS id,
            Elem AS elem,
            Magic AS magic
        FROM LINK_ElemsMagics
    ]]
}

function get_link_elems_magics.execute(_, response)
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_link_elems_magics.query)
    local link_elems_magics = mapper.fetch_results.as_object(result, prototype)

    response:write(json.encode(link_elems_magics))
    result:close()
    connection:close()
    env:close()
end

return get_link_elems_magics
