---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 11/03/2024 11:03
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local prototype = require('entities.link_elems_magics')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')
local errors = require('utils.errors')

local put_link_elems_magics = {
    vocab = {
        table_name = "LINK_ElemsMagics",
        primary_key = { db = "ID", prop = "id" },
        editable_columns = {
            elem = "Elem",
            magic = "Magic"
        }
    }
}

function put_link_elems_magics.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local edited_links = json.decode(request:receiveBody())
    local queries = query_builder.create_update_queries(
            put_link_elems_magics.vocab,
            prototype,
            edited_links,
            escaper
    )

    if type(queries) ~= "string" then
        errors.incorrect_data(response, { link_elems_magics = queries }, connection, env)
        return
    end
    if not connection:execute(queries) then
        errors.foreign_value_not_found(
                response,
                { "element", "magic", "link between element and magic" },
                connection,
                env
        )
        return
    end

    response:sendOnlyHeaders()
    put_link_elems_magics.close(connection, env)
end

function put_link_elems_magics.close(connection, env)
    connection:close()
    env:close()
end

return put_link_elems_magics
