---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 23/02/2024 23:33
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local mapper = require('utils.mapper')

local get_elems = {
    query = [[
        SELECT
            ID AS id,
            Name AS name
        FROM Elems
    ]]
}

function get_elems.execute(_, response)
    local connection, env = connector.create()
    if not connection then return end

    local result = connection:execute(get_elems.query)
    local elems = mapper.fetch_results.as_table(result, {
        id = tonumber
    })

    response:write(json.encode(elems))
    result:close()
    connection:close()
    env:close()
end

return get_elems