---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 17/02/2024 12:49
---
return {
    calendar = "Calendars",
    charac_event = "CharacEvents",
    charac = "Characs",
    charac_relationship = "CharacsRelationships",
    class = "Classes",
    elem = "Elems",
    family_status = "FamilyStatuses",
    gender = "Genders",
    link_charac_magic = "LINK_CharacsMagics",
    link_elem_magic = "LINK_ElemsMagics",
    magic = "Magics",
    map = "Maps",
    nation = "Nations",
    nation_leader = "NationLeaders",
    sex = "Sexes"
}
