---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 18/02/2024 19:38
---
return function (table)
    local new_table = {}

    for k,v in pairs(table) do
        new_table[k] = v
    end

    return new_table
end
