---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 18/02/2024 01:28
---
local database_connection = {}
local mysql_driver = require('luasql.mysql')
local logger = require('utils.logger')

local database = require('config.database')

function database_connection.create()
    local env = mysql_driver.mysql()
    local connection = env:connect(database.source_name, database.username, database.password)

    if not connection then
        env:close()
        database_connection.handle_connection_failure()
        return nil
    end

    return connection, env -- to be able to close it from outside
end

function database_connection.handle_connection_failure()
    logger.log(logger.levels.ERROR, "Could not connect to the database! Check the configuration files!")
end

return database_connection
