---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 18/02/2024 17:19
---
local data_checker = {}

function data_checker.ensure_model_compliance(entity, model, extra_function)
    for key, property in pairs(model) do
        if not property.nullable and entity[key] == nil then error("nil value found!") end
        entity[key] = extra_function(entity[key])
    end
end

return data_checker
