---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 08/03/2024 14:37
---
local http = require('enums.http_facade')
local json = require('lunajson')

local errors = {}

function errors.lacking_data(response, attachment, connection, env)
    response
            :statusCode(http.codes.BAD_REQUEST)
            :write(json.encode({ message = "Detected missing values in this entity", attachment = attachment }))
    errors.close_database_connection(connection, env)
end

function errors.incorrect_data(response, attachment, connection, env)
    response
            :statusCode(http.codes.BAD_REQUEST)
            :write(json.encode({ message = "Detected incorrect values in this entity", attachment = attachment }))
    errors.close_database_connection(connection, env)
end

function errors.foreign_value_not_found(response, foreign_entities, connection, env)
    response
            :statusCode(http.codes.NOT_FOUND)
            :write(json.encode({ message = "One of the following foreign entity couldn't be found in the database", foreign_entities = foreign_entities }))
    errors.close_database_connection(connection, env)
end

function errors.close_database_connection(connection, env)
    connection:close()
    env:close()
end

return errors
