---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 18/02/2024 20:17
---
local escape = {}
local logger = require('utils.logger')

function escape.set_connection(connection)
    escape.connection = connection
end

function escape.apply(field)
    if type(field) == "string" then
        field = escape.connection:escape(field)
    end
    return field
end

return escape
