---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 18/02/2024 00:56
---
local api_key = require('config.api_key')

local security = {}

function security.check_key(request, authentication_needed)
    local given_key = request:headers()["API-KEY"]
    return (not authentication_needed) or given_key == api_key
end

return security
