---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 17/02/2024 14:05
---
return {
    days = {
        name = "days",
        shortname = "d",
        from_days = 1,
        from_hours = (1/24),
        from_minutes = (1/1440),
        from_seconds = (1/86400),
        from_milliseconds = (1/86400000)
    },

    hours = {
        name = "hours",
        shortname = "h",
        from_days = 24,
        from_hours = 1,
        from_minutes = (1/60),
        from_seconds = (1/3600),
        from_milliseconds = (1/3600000)
    },

    minutes = {
        name = "minutes",
        shortname = "mn",
        from_days = 1440,
        from_hours = 60,
        from_minutes = 1,
        from_seconds = (1/60),
        from_milliseconds = (1/60000)
    },

    seconds = {
        name = "seconds",
        shortname = "s",
        from_days = 86400,
        from_hours = 3600,
        from_minutes = 60,
        from_seconds = 1,
        from_milliseconds = (1/1000)
    },

    milliseconds = {
        name = "milliseconds",
        shortname = "ms",
        from_days = 86400000,
        from_hours = 3600000,
        from_minutes = 60000,
        from_seconds = 1000,
        from_milliseconds = 1
    }
}
