---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 07/03/2024 21:49
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local http = require('enums.http_facade')
local prototype = require('entities.nation_leader')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')

local post_nation_leaders = {
    query = [[
        INSERT INTO NationsLeaders
        (
            Leader,
            Nation,
            LeadStartDate,
            LeadEndDate
        )
        VALUES

    ]],

    value = "(%s, %s, %s, %s)"
}

function post_nation_leaders.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local new_nation_leaders = json.decode(request:receiveBody())
    local query = query_builder.create_insert_query(
            post_nation_leaders.query,
            post_nation_leaders.value,
            prototype,
            new_nation_leaders,
            escaper
    )


    if type(query) ~= "string" then
        post_nation_leaders.lacking_data(response, query, connection, env)
        return
    end
    if not connection:execute(query) then
        post_nation_leaders.foreign_value_not_found(response, connection, env)
        return
    end

    response
            :statusCode(http.codes.CREATED)
            :sendOnlyHeaders()
    post_nation_leaders.close(connection, env)
end

function post_nation_leaders.lacking_data(response, entity, connection, env)
    response
            :statusCode(http.codes.BAD_REQUEST)
            :write(json.encode({ message = "Detected missing values in this entity", nation_leader = entity }))
    post_nation_leaders.close(connection, env)
end

function post_nation_leaders.foreign_value_not_found(response, connection, env)
    response
            :statusCode(http.codes.NOT_FOUND)
            :write(json.encode({ message = "Leader or nation not found!" }))
    post_nation_leaders.close(connection, env)
end

function post_nation_leaders.close(connection, env)
    connection:close()
    env:close()
end

return post_nation_leaders
