---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 11/03/2024 11:52
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local prototype = require('entities.nation_leader')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')
local errors = require('utils.errors')

local put_nation_leaders = {
    vocab = {
        table_name = "NationsLeaders",
        primary_key = { db = "ID", prop = "id" },
        editable_columns = {
            leader = "Leader",
            nation = "Nation",
            lead_start_date = "LeadStartDate",
            lead_end_date = "LeadEndDate"
        }
    }
}

function put_nation_leaders.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local edited_nation_leaders = json.decode(request:receiveBody())
    local queries = query_builder.create_update_queries(
            put_nation_leaders.vocab,
            prototype,
            edited_nation_leaders,
            escaper
    )

    if type(queries) ~= "string" then
        errors.incorrect_data(response, { nation_leader = queries }, connection, env)
        return
    end
    if not connection:execute(queries) then
        errors.foreign_value_not_found(
                response,
                { "leader", "nation", "nation leader" },
                connection,
                env
        )
        return
    end

    response:sendOnlyHeaders()
    put_nation_leaders.close(connection, env)
end

function put_nation_leaders.close(connection, env)
    connection:close()
    env:close()
end

return put_nation_leaders
