---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 05/03/2024 13:24
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local http = require('enums.http_facade')
local prototype = require('entities.charac_relationship')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')

local post_charac_relationships = {
    query = [[
        INSERT INTO CharacsRelationships
        (
            FromCharac,
            TowardsCharac,
            FamilyStatus,
            Appreciation,
            History
        )
        VALUES

    ]],

    value = "(%s, %s, %s, %s, %s)"
}

function post_charac_relationships.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local new_charac_relationships = json.decode(request:receiveBody())
    local query = query_builder.create_insert_query(
            post_charac_relationships.query,
            post_charac_relationships.value,
            prototype,
            new_charac_relationships,
            escaper
    )

    if type(query) ~= "string" then
        post_charac_relationships.lacking_data(response, query, connection, env)
        return
    end
    if not connection:execute(query) then
        post_charac_relationships.foreign_value_not_found(response, connection, env)
        return
    end

    response
            :statusCode(http.codes.CREATED)
            :sendOnlyHeaders()
    post_charac_relationships.close(connection, env)
end

function post_charac_relationships.lacking_data(response, entity, connection, env)
    response
            :statusCode(http.codes.BAD_REQUEST)
            :write(json.encode({ message = "Detected missing values in this entity", character_relationship = entity }))
    post_charac_relationships.close(connection, env)
end

function post_charac_relationships.foreign_value_not_found(response, connection, env)
    response
            :statusCode(http.codes.NOT_FOUND)
            :write(json.encode({ message = "Characters or family status not found!" }))
    post_charac_relationships.close(connection, env)
end

function post_charac_relationships.close(connection, env)
    connection:close()
    env:close()
end

return post_charac_relationships
