---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 22/02/2024 10:50
---
local url = require('url')
local connector = require('utils.database_connection')
local logger = require('utils.logger')

local delete = {
    query = [[
        DELETE FROM %s
        WHERE %s IN (%s)
    ]]
}

function delete.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    if not delete.queried_table or not delete.id_column or not delete.querystring_property_name then
        logger.log(logger.levels.ERROR, "Missing property when calling the execute function of the generic delete use case!")
        return false
    end

    local ids = string.sub(url.decode(request.querystring[delete.querystring_property_name]), 2, -2)
    local success = connection:execute(string.format(
            delete.query,
            delete.queried_table,
            delete.id_column,
            ids
    ))

    connection:close()
    env:close()
    return success
end

function delete.set_queried_table(table_name)
    delete.queried_table = table_name
    return delete
end

function delete.set_id_column(column_name)
    delete.id_column = column_name
    return delete
end

function delete.set_querystring_property_name(property_name)
    delete.querystring_property_name = property_name
    return delete
end

return delete
