---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 16/03/2024 00:45
---
local access_control = require('config.access_control')

local options = {}

function options.execute(_, response)
    if access_control.allow_origin then response:addHeader("Access-Control-Allow-Origin", access_control.allow_origin) end
    if access_control.allow_methods then response:addHeader("Access-Control-Allow-Methods", access_control.allow_methods) end
    if access_control.allow_headers then response:addHeader("Access-Control-Allow-Headers", access_control.allow_headers) end

    response:sendOnlyHeaders()
end

return options
