---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 07/03/2024 21:02
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local http = require('enums.http_facade')
local prototype = require('entities.magic')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')

local post_magics = {
    query = [[
        INSERT INTO Magics
        (
            Name,
            Description
        )
        VALUES

    ]],

    value = "(%s, %s)"
}

function post_magics.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local new_magics = json.decode(request:receiveBody())
    local query = query_builder.create_insert_query(
            post_magics.query,
            post_magics.value,
            prototype,
            new_magics,
            escaper
    )


    if type(query) ~= "string" then
        post_magics.lacking_data(response, query, connection, env)
        return
    end
    if not connection:execute(query) then
        post_magics.could_not_process(response, connection, env)
        return
    end

    response
            :statusCode(http.codes.CREATED)
            :sendOnlyHeaders()
    post_magics.close(connection, env)
end

function post_magics.lacking_data(response, entity, connection, env)
    response
            :statusCode(http.codes.BAD_REQUEST)
            :write(json.encode({ message = "Detected missing values in this entity", magic = entity }))
    post_magics.close(connection, env)
end

function post_magics.could_not_process(response, connection, env)
    response
            :statusCode(http.codes.NOT_FOUND)
            :write(json.encode({ message = "Something went wrong when trying to add those magics to the list..." }))
    post_magics.close(connection, env)
end

function post_magics.close(connection, env)
    connection:close()
    env:close()
end

return post_magics
