---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RedNeath.
--- DateTime: 11/03/2024 11:14
---
local json = require('lunajson')
local connector = require('utils.database_connection')
local prototype = require('entities.magic')
local escaper = require('utils.extra_function_escape')
local query_builder = require('utils.query_builder')
local errors = require('utils.errors')

local put_magics = {
    vocab = {
        table_name = "Magics",
        primary_key = { db = "ID", prop = "id" },
        editable_columns = {
            name = "Name",
            description = "Description"
        }
    }
}

function put_magics.execute(request, response)
    local connection, env = connector.create()
    if not connection then return end
    escaper.set_connection(connection)

    local edited_magics = json.decode(request:receiveBody())
    local queries = query_builder.create_update_queries(
            put_magics.vocab,
            prototype,
            edited_magics,
            escaper
    )

    if type(queries) ~= "string" then
        errors.incorrect_data(response, { magic = queries }, connection, env)
        return
    end
    if not connection:execute(queries) then
        errors.foreign_value_not_found(
                response,
                { "magic" },
                connection,
                env
        )
        return
    end

    response:sendOnlyHeaders()
    put_magics.close(connection, env)
end

function put_magics.close(connection, env)
    connection:close()
    env:close()
end

return put_magics
